version: '3'

services:

    db:
        image: mysql
        container_name: db_docker_symfony
        restart: always
        volumes:
            - db-data:/Setup xampp/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony
        restart: always
        depends_on: 
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: